from __future__ import annotations
from typing import Protocol, Any

class Publisher(Protocol):
    def publishMap(self, mapData: dict) -> None: ...

    def publishCurPos(self, posData: dict) -> None: ...

    def publishCurMovingStatus(self, movingStatusData: int) -> None: ...

    def publishCurStatus(self, statusData: dict) -> None: ...

    def publishCurBatteryPercent(self, battery: float) -> None: ...

