#!/usr/bin/env bash
set -euo pipefail

# Configure the Orange Pi LAN as a NetworkManager shared connection. This
# provides DHCP on 192.168.10.0/24 and keeps the Jetson default route on Wi-Fi.
source /usr/local/lib/orangepi-network-common.sh

if [ "${1:-}" = "--print-lan-if" ]; then
  orangepi_find_lan_if
  exit 0
fi

LAN_IF="$(orangepi_find_lan_if)"
if [ -z "$LAN_IF" ]; then
  orangepi_log "no USB ${ORANGEPI_USB_DRIVER} LAN adapter found"
  exit 0
fi

if ! nmcli -t -f NAME connection show | grep -Fxq "$ORANGEPI_NM_CONNECTION"; then
  nmcli connection add type ethernet ifname "$LAN_IF" con-name "$ORANGEPI_NM_CONNECTION"
fi

nmcli connection modify "$ORANGEPI_NM_CONNECTION" \
  connection.interface-name "$LAN_IF" \
  connection.autoconnect yes \
  connection.autoconnect-priority 100 \
  ipv4.method shared \
  ipv4.addresses "$ORANGEPI_LAN_ADDR" \
  ipv4.never-default yes \
  ipv6.method disabled

# Disable autogenerated DHCP-client profiles on the Orange Pi USB adapter.
nmcli -t -f NAME,DEVICE,TYPE connection show --active \
  | while IFS=: read -r name device type; do
      [ "$device" = "$LAN_IF" ] || continue
      [ "$type" = "802-3-ethernet" ] || continue
      [ "$name" != "$ORANGEPI_NM_CONNECTION" ] || continue
      nmcli connection down "$name" || true
      nmcli connection modify "$name" connection.autoconnect no || true
    done

nmcli connection up "$ORANGEPI_NM_CONNECTION" ifname "$LAN_IF"
/usr/local/sbin/orangepi-nat.sh

orangepi_log "shared LAN ready: ${LAN_IF} ${ORANGEPI_LAN_ADDR}"
